source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'LiveStreamingDemo' do
    
  pod 'LFLiveKit'
  pod 'Socket.IO-Client-Swift'
  pod 'SnapKit' #自动布局
  pod 'Alamofire' #http网络请求
  pod 'HandyJSON' #json解析
  pod 'lottie-ios' #动画
  
end
